# Generated by Django 2.0.4 on 2018-04-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornesedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=20)),
                ('morada', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('Nasaun', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornesedor',
        ),
        migrations.AddField(
            model_name='produto',
            name='kategoria',
            field=models.CharField(choices=[('IT', 'IT Equipment'), ('OT', 'Office Stationary'), ('OTS', 'Others')], default='IT Equipment', max_length=10),
        ),
    ]
