# Generated by Django 2.0.4 on 2018-04-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180420_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Titulo'),
        ),
    ]
