# Generated by Django 2.0.4 on 2018-04-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskrisaun', models.CharField(max_length=255)),
                ('fornesedor', models.CharField(choices=[('IT Equipment', 'IT'), ('Office Stationary', 'OT'), ('Others', 'OTS')], default='IT Equipment', max_length=10)),
            ],
        ),
    ]
